// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: service.proto

package consolepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConsoleService_GetAgentManifest_FullMethodName = "/rune.console.v1.ConsoleService/GetAgentManifest"
	ConsoleService_Insert_FullMethodName           = "/rune.console.v1.ConsoleService/Insert"
	ConsoleService_Search_FullMethodName           = "/rune.console.v1.ConsoleService/Search"
	ConsoleService_GetCentroids_FullMethodName     = "/rune.console.v1.ConsoleService/GetCentroids"
)

// ConsoleServiceClient is the client API for ConsoleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Rune-console gRPC service.
// The console generates and custodies the FHE key set. The PUBLIC EncKey and
// the caller's derived agent_dek are handed to rune-mcp via GetAgentManifest
// so capture encryption/sealing happens on the developer machine; SecKey,
// EvalKey, and team_secret never leave this server. The console is the SOLE
// runespace client — rune-mcp talks only to this service and forwards
// ciphertext through it.
type ConsoleServiceClient interface {
	// Returns the agent manifest: EncKey (RMP+MM, public), the caller's
	// agent_dek, index config, centroid_set_version, and capability flags.
	GetAgentManifest(ctx context.Context, in *GetAgentManifestRequest, opts ...grpc.CallOption) (*GetAgentManifestResponse, error)
	// Capture write: forward a client-encrypted item (EncryptFlat +
	// EncryptClustered blobs, plaintext cluster routing, sealed metadata)
	// verbatim to runespace. The console sees no plaintext content.
	Insert(ctx context.Context, in *InsertRequest, opts ...grpc.CallOption) (*InsertResponse, error)
	// Blind vector search over runespace (recall + capture-time novelty check).
	// The plaintext query is sent to runespace (PCMM); the console decrypts the
	// score blobs (SecKey), ranks, resolves and opens metadata (agent_dek), and
	// returns ranked plaintext hits.
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	// Relays the runespace IVF centroid set (header, then id-ordered batches)
	// so rune-mcp can push it down to runed for insert routing. Public
	// structural data — same wire shape as runespace's GetCentroids.
	GetCentroids(ctx context.Context, in *GetCentroidsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CentroidChunk], error)
}

type consoleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewConsoleServiceClient(cc grpc.ClientConnInterface) ConsoleServiceClient {
	return &consoleServiceClient{cc}
}

func (c *consoleServiceClient) GetAgentManifest(ctx context.Context, in *GetAgentManifestRequest, opts ...grpc.CallOption) (*GetAgentManifestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAgentManifestResponse)
	err := c.cc.Invoke(ctx, ConsoleService_GetAgentManifest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consoleServiceClient) Insert(ctx context.Context, in *InsertRequest, opts ...grpc.CallOption) (*InsertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InsertResponse)
	err := c.cc.Invoke(ctx, ConsoleService_Insert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consoleServiceClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, ConsoleService_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consoleServiceClient) GetCentroids(ctx context.Context, in *GetCentroidsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CentroidChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ConsoleService_ServiceDesc.Streams[0], ConsoleService_GetCentroids_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetCentroidsRequest, CentroidChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConsoleService_GetCentroidsClient = grpc.ServerStreamingClient[CentroidChunk]

// ConsoleServiceServer is the server API for ConsoleService service.
// All implementations must embed UnimplementedConsoleServiceServer
// for forward compatibility.
//
// Rune-console gRPC service.
// The console generates and custodies the FHE key set. The PUBLIC EncKey and
// the caller's derived agent_dek are handed to rune-mcp via GetAgentManifest
// so capture encryption/sealing happens on the developer machine; SecKey,
// EvalKey, and team_secret never leave this server. The console is the SOLE
// runespace client — rune-mcp talks only to this service and forwards
// ciphertext through it.
type ConsoleServiceServer interface {
	// Returns the agent manifest: EncKey (RMP+MM, public), the caller's
	// agent_dek, index config, centroid_set_version, and capability flags.
	GetAgentManifest(context.Context, *GetAgentManifestRequest) (*GetAgentManifestResponse, error)
	// Capture write: forward a client-encrypted item (EncryptFlat +
	// EncryptClustered blobs, plaintext cluster routing, sealed metadata)
	// verbatim to runespace. The console sees no plaintext content.
	Insert(context.Context, *InsertRequest) (*InsertResponse, error)
	// Blind vector search over runespace (recall + capture-time novelty check).
	// The plaintext query is sent to runespace (PCMM); the console decrypts the
	// score blobs (SecKey), ranks, resolves and opens metadata (agent_dek), and
	// returns ranked plaintext hits.
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	// Relays the runespace IVF centroid set (header, then id-ordered batches)
	// so rune-mcp can push it down to runed for insert routing. Public
	// structural data — same wire shape as runespace's GetCentroids.
	GetCentroids(*GetCentroidsRequest, grpc.ServerStreamingServer[CentroidChunk]) error
	mustEmbedUnimplementedConsoleServiceServer()
}

// UnimplementedConsoleServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConsoleServiceServer struct{}

func (UnimplementedConsoleServiceServer) GetAgentManifest(context.Context, *GetAgentManifestRequest) (*GetAgentManifestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAgentManifest not implemented")
}
func (UnimplementedConsoleServiceServer) Insert(context.Context, *InsertRequest) (*InsertResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Insert not implemented")
}
func (UnimplementedConsoleServiceServer) Search(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedConsoleServiceServer) GetCentroids(*GetCentroidsRequest, grpc.ServerStreamingServer[CentroidChunk]) error {
	return status.Error(codes.Unimplemented, "method GetCentroids not implemented")
}
func (UnimplementedConsoleServiceServer) mustEmbedUnimplementedConsoleServiceServer() {}
func (UnimplementedConsoleServiceServer) testEmbeddedByValue()                        {}

// UnsafeConsoleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConsoleServiceServer will
// result in compilation errors.
type UnsafeConsoleServiceServer interface {
	mustEmbedUnimplementedConsoleServiceServer()
}

func RegisterConsoleServiceServer(s grpc.ServiceRegistrar, srv ConsoleServiceServer) {
	// If the following call panics, it indicates UnimplementedConsoleServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConsoleService_ServiceDesc, srv)
}

func _ConsoleService_GetAgentManifest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAgentManifestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsoleServiceServer).GetAgentManifest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConsoleService_GetAgentManifest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsoleServiceServer).GetAgentManifest(ctx, req.(*GetAgentManifestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConsoleService_Insert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsoleServiceServer).Insert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConsoleService_Insert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsoleServiceServer).Insert(ctx, req.(*InsertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConsoleService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsoleServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConsoleService_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsoleServiceServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConsoleService_GetCentroids_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetCentroidsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ConsoleServiceServer).GetCentroids(m, &grpc.GenericServerStream[GetCentroidsRequest, CentroidChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConsoleService_GetCentroidsServer = grpc.ServerStreamingServer[CentroidChunk]

// ConsoleService_ServiceDesc is the grpc.ServiceDesc for ConsoleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConsoleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rune.console.v1.ConsoleService",
	HandlerType: (*ConsoleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAgentManifest",
			Handler:    _ConsoleService_GetAgentManifest_Handler,
		},
		{
			MethodName: "Insert",
			Handler:    _ConsoleService_Insert_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _ConsoleService_Search_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetCentroids",
			Handler:       _ConsoleService_GetCentroids_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "service.proto",
}
