# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vault_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'vault_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13vault_service.proto\x12\rrune.vault.v1\"$\n\x13GetPublicKeyRequest\x12\r\n\x05token\x18\x01 \x01(\t\">\n\x14GetPublicKeyResponse\x12\x17\n\x0fkey_bundle_json\x18\x01 \x01(\t\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"P\n\x14\x44\x65\x63ryptScoresRequest\x12\r\n\x05token\x18\x01 \x01(\t\x12\x1a\n\x12\x65ncrypted_blob_b64\x18\x02 \x01(\t\x12\r\n\x05top_k\x18\x03 \x01(\x05\"?\n\nScoreEntry\x12\x11\n\tshard_idx\x18\x01 \x01(\x05\x12\x0f\n\x07row_idx\x18\x02 \x01(\x05\x12\r\n\x05score\x18\x03 \x01(\x01\"R\n\x15\x44\x65\x63ryptScoresResponse\x12*\n\x07results\x18\x01 \x03(\x0b\x32\x19.rune.vault.v1.ScoreEntry\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"H\n\x16\x44\x65\x63ryptMetadataRequest\x12\r\n\x05token\x18\x01 \x01(\t\x12\x1f\n\x17\x65ncrypted_metadata_list\x18\x02 \x03(\t\"D\n\x17\x44\x65\x63ryptMetadataResponse\x12\x1a\n\x12\x64\x65\x63rypted_metadata\x18\x01 \x03(\t\x12\r\n\x05\x65rror\x18\x02 \x01(\t2\xa5\x02\n\x0cVaultService\x12W\n\x0cGetPublicKey\x12\".rune.vault.v1.GetPublicKeyRequest\x1a#.rune.vault.v1.GetPublicKeyResponse\x12Z\n\rDecryptScores\x12#.rune.vault.v1.DecryptScoresRequest\x1a$.rune.vault.v1.DecryptScoresResponse\x12`\n\x0f\x44\x65\x63ryptMetadata\x12%.rune.vault.v1.DecryptMetadataRequest\x1a&.rune.vault.v1.DecryptMetadataResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vault_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETPUBLICKEYREQUEST']._serialized_start=38
  _globals['_GETPUBLICKEYREQUEST']._serialized_end=74
  _globals['_GETPUBLICKEYRESPONSE']._serialized_start=76
  _globals['_GETPUBLICKEYRESPONSE']._serialized_end=138
  _globals['_DECRYPTSCORESREQUEST']._serialized_start=140
  _globals['_DECRYPTSCORESREQUEST']._serialized_end=220
  _globals['_SCOREENTRY']._serialized_start=222
  _globals['_SCOREENTRY']._serialized_end=285
  _globals['_DECRYPTSCORESRESPONSE']._serialized_start=287
  _globals['_DECRYPTSCORESRESPONSE']._serialized_end=369
  _globals['_DECRYPTMETADATAREQUEST']._serialized_start=371
  _globals['_DECRYPTMETADATAREQUEST']._serialized_end=443
  _globals['_DECRYPTMETADATARESPONSE']._serialized_start=445
  _globals['_DECRYPTMETADATARESPONSE']._serialized_end=513
  _globals['_VAULTSERVICE']._serialized_start=516
  _globals['_VAULTSERVICE']._serialized_end=809
# @@protoc_insertion_point(module_scope)
