"""
Integration tests for the decrypt pipeline.

Uses pre-generated fixtures from tests/fixtures/ (captured from enVector Cloud)
to test _decrypt_scores_impl and _decrypt_metadata_impl end-to-end.

Fixtures are generated by: scripts/generate-test-fixtures.py
"""

import json
import os
import sys

import pytest

# Add vault to path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "../../vault"))

FIXTURES_DIR = os.path.join(os.path.dirname(__file__), "..", "fixtures")


def _load_fixture(name: str) -> str | dict | list:
    path = os.path.join(FIXTURES_DIR, name)
    with open(path) as f:
        if name.endswith(".json"):
            return json.load(f)
        return f.read().strip()


@pytest.fixture(scope="module")
def fixtures():
    """Load all fixtures and patch vault_core for testing."""
    config = _load_fixture("config.json")
    keys_dir = os.path.join(FIXTURES_DIR, "keys")
    return {
        "config": config,
        "enc_key_path": os.path.join(keys_dir, "EncKey.json"),
        "sec_key_path": os.path.join(keys_dir, "SecKey.json"),
        "score_blob_b64": _load_fixture("ciphertext_score.b64"),
        "expected_scores": _load_fixture("expected_scores.json"),
        "envelopes": _load_fixture("metadata_envelopes.json"),
        "expected_metadata": _load_fixture("expected_metadata.json"),
    }


@pytest.fixture(autouse=True)
def patch_vault(fixtures, monkeypatch):
    """Patch vault_core to use fixture keys and config."""
    import vault_core
    from pyenvector.crypto import Cipher
    from token_store import token_store

    config = fixtures["config"]

    monkeypatch.setattr(vault_core, "sec_key_path", fixtures["sec_key_path"])
    monkeypatch.setattr(vault_core, "VAULT_TEAM_SECRET", config["team_secret"])

    # Reinitialize cipher with fixture SecKey (dim must match fixture FHE dim)
    # cipher.decrypt_score needs enc_key_path but only uses sec_key_path for decryption
    # Use a dummy enc_key_path since we only decrypt
    fixture_cipher = Cipher(enc_key_path=fixtures["enc_key_path"], dim=config["fhe_dim"])
    monkeypatch.setattr(vault_core, "cipher", fixture_cipher)

    token_store._rate_limiters.clear()


class TestDecryptScores:

    def test_decrypt_scores(self, fixtures):
        """Full pipeline: CiphertextScore blob → _decrypt_scores_impl → correct scores."""
        from vault_core import _decrypt_scores_impl

        config = fixtures["config"]
        expected = fixtures["expected_scores"]
        total_scores = sum(len(row) for row in expected["score"])

        result = _decrypt_scores_impl(config["token"], fixtures["score_blob_b64"], top_k=total_scores)
        data = json.loads(result)

        assert isinstance(data, list)
        assert len(data) == total_scores

        # Verify scores match expected (FHE decryption is deterministic with same key)
        expected_flat = []
        shard_indices = expected["shard_idx"]
        for i, row in enumerate(expected["score"]):
            for j, score in enumerate(row):
                expected_flat.append((shard_indices[i], j, score))
        expected_flat.sort(key=lambda x: x[2], reverse=True)

        for actual, (exp_shard, exp_row, exp_score) in zip(data, expected_flat):
            assert actual["shard_idx"] == exp_shard
            assert actual["row_idx"] == exp_row
            assert abs(actual["score"] - exp_score) < 1e-6

    def test_decrypt_scores_top_k(self, fixtures):
        """Top-K filtering returns correct count and highest scores."""
        from vault_core import _decrypt_scores_impl

        config = fixtures["config"]
        expected = fixtures["expected_scores"]

        # Get all scores to find the true top-3
        all_scores = []
        for i, row in enumerate(expected["score"]):
            for j, score in enumerate(row):
                all_scores.append(score)
        all_scores.sort(reverse=True)

        result = _decrypt_scores_impl(config["token"], fixtures["score_blob_b64"], top_k=3)
        data = json.loads(result)

        assert len(data) == 3
        # Returned scores should be the 3 highest
        returned_scores = [item["score"] for item in data]
        for actual, expected_score in zip(returned_scores, all_scores[:3]):
            assert abs(actual - expected_score) < 1e-6
        # Descending order
        assert returned_scores == sorted(returned_scores, reverse=True)


class TestDecryptMetadata:

    def test_decrypt_metadata_single(self, fixtures):
        """Single envelope → _decrypt_metadata_impl → correct plaintext."""
        from vault_core import _decrypt_metadata_impl

        config = fixtures["config"]
        envelopes = fixtures["envelopes"]
        expected = fixtures["expected_metadata"]

        result = _decrypt_metadata_impl(config["token"], [envelopes[0]])
        data = json.loads(result)

        assert isinstance(data, list)
        assert len(data) == 1
        # _decrypt_metadata_impl returns JSON strings or already-decoded objects
        actual = json.loads(data[0]) if isinstance(data[0], str) else data[0]
        assert actual == expected[0]

    def test_decrypt_metadata_multiple(self, fixtures):
        """Multiple envelopes → all decrypted correctly."""
        from vault_core import _decrypt_metadata_impl

        config = fixtures["config"]
        envelopes = fixtures["envelopes"]
        expected = fixtures["expected_metadata"]

        result = _decrypt_metadata_impl(config["token"], envelopes)
        data = json.loads(result)

        assert len(data) == len(expected)
        for item, exp in zip(data, expected):
            actual = json.loads(item) if isinstance(item, str) else item
            assert actual == exp
