// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: vault_service.proto

package vaultpb

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPublicKeyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Auth token. Required, Fixed 36 chars (evt_ + 32 hex).
	Token         string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublicKeyRequest) Reset() {
	*x = GetPublicKeyRequest{}
	mi := &file_vault_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublicKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublicKeyRequest) ProtoMessage() {}

func (x *GetPublicKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vault_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublicKeyRequest.ProtoReflect.Descriptor instead.
func (*GetPublicKeyRequest) Descriptor() ([]byte, []int) {
	return file_vault_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetPublicKeyRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type GetPublicKeyResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// JSON string: {"EncKey.json": "...", "EvalKey.json": "...", "index_name": "..."}
	KeyBundleJson string `protobuf:"bytes,1,opt,name=key_bundle_json,json=keyBundleJson,proto3" json:"key_bundle_json,omitempty"`
	Error         string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"` // Non-empty on error
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublicKeyResponse) Reset() {
	*x = GetPublicKeyResponse{}
	mi := &file_vault_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublicKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublicKeyResponse) ProtoMessage() {}

func (x *GetPublicKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vault_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublicKeyResponse.ProtoReflect.Descriptor instead.
func (*GetPublicKeyResponse) Descriptor() ([]byte, []int) {
	return file_vault_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetPublicKeyResponse) GetKeyBundleJson() string {
	if x != nil {
		return x.KeyBundleJson
	}
	return ""
}

func (x *GetPublicKeyResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DecryptScoresRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Auth token. Required, Fixed 36 chars (evt_ + 32 hex).
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// Base64-encoded CiphertextScore protobuf. Required.
	EncryptedBlobB64 string `protobuf:"bytes,2,opt,name=encrypted_blob_b64,json=encryptedBlobB64,proto3" json:"encrypted_blob_b64,omitempty"`
	// Number of top results to return.
	// Per-role limits (e.g., admin=50, member=10) enforced at the business logic layer.
	TopK          int32 `protobuf:"varint,3,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecryptScoresRequest) Reset() {
	*x = DecryptScoresRequest{}
	mi := &file_vault_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecryptScoresRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecryptScoresRequest) ProtoMessage() {}

func (x *DecryptScoresRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vault_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecryptScoresRequest.ProtoReflect.Descriptor instead.
func (*DecryptScoresRequest) Descriptor() ([]byte, []int) {
	return file_vault_service_proto_rawDescGZIP(), []int{2}
}

func (x *DecryptScoresRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *DecryptScoresRequest) GetEncryptedBlobB64() string {
	if x != nil {
		return x.EncryptedBlobB64
	}
	return ""
}

func (x *DecryptScoresRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

type ScoreEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardIdx      int32                  `protobuf:"varint,1,opt,name=shard_idx,json=shardIdx,proto3" json:"shard_idx,omitempty"`
	RowIdx        int32                  `protobuf:"varint,2,opt,name=row_idx,json=rowIdx,proto3" json:"row_idx,omitempty"`
	Score         float64                `protobuf:"fixed64,3,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoreEntry) Reset() {
	*x = ScoreEntry{}
	mi := &file_vault_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoreEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreEntry) ProtoMessage() {}

func (x *ScoreEntry) ProtoReflect() protoreflect.Message {
	mi := &file_vault_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreEntry.ProtoReflect.Descriptor instead.
func (*ScoreEntry) Descriptor() ([]byte, []int) {
	return file_vault_service_proto_rawDescGZIP(), []int{3}
}

func (x *ScoreEntry) GetShardIdx() int32 {
	if x != nil {
		return x.ShardIdx
	}
	return 0
}

func (x *ScoreEntry) GetRowIdx() int32 {
	if x != nil {
		return x.RowIdx
	}
	return 0
}

func (x *ScoreEntry) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

type DecryptScoresResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*ScoreEntry          `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"` // Top-K results sorted by score descending
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`     // Non-empty on error
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecryptScoresResponse) Reset() {
	*x = DecryptScoresResponse{}
	mi := &file_vault_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecryptScoresResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecryptScoresResponse) ProtoMessage() {}

func (x *DecryptScoresResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vault_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecryptScoresResponse.ProtoReflect.Descriptor instead.
func (*DecryptScoresResponse) Descriptor() ([]byte, []int) {
	return file_vault_service_proto_rawDescGZIP(), []int{4}
}

func (x *DecryptScoresResponse) GetResults() []*ScoreEntry {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *DecryptScoresResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DecryptMetadataRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Auth token. Required, Fixed 36 chars (evt_ + 32 hex).
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// Base64-encoded AES blobs. Required, max 1000 items, each non-empty.
	EncryptedMetadataList []string `protobuf:"bytes,2,rep,name=encrypted_metadata_list,json=encryptedMetadataList,proto3" json:"encrypted_metadata_list,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *DecryptMetadataRequest) Reset() {
	*x = DecryptMetadataRequest{}
	mi := &file_vault_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecryptMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecryptMetadataRequest) ProtoMessage() {}

func (x *DecryptMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vault_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecryptMetadataRequest.ProtoReflect.Descriptor instead.
func (*DecryptMetadataRequest) Descriptor() ([]byte, []int) {
	return file_vault_service_proto_rawDescGZIP(), []int{5}
}

func (x *DecryptMetadataRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *DecryptMetadataRequest) GetEncryptedMetadataList() []string {
	if x != nil {
		return x.EncryptedMetadataList
	}
	return nil
}

type DecryptMetadataResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Each element is a JSON-serialized decrypted metadata object
	DecryptedMetadata []string `protobuf:"bytes,1,rep,name=decrypted_metadata,json=decryptedMetadata,proto3" json:"decrypted_metadata,omitempty"`
	Error             string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"` // Non-empty on error
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DecryptMetadataResponse) Reset() {
	*x = DecryptMetadataResponse{}
	mi := &file_vault_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecryptMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecryptMetadataResponse) ProtoMessage() {}

func (x *DecryptMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vault_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecryptMetadataResponse.ProtoReflect.Descriptor instead.
func (*DecryptMetadataResponse) Descriptor() ([]byte, []int) {
	return file_vault_service_proto_rawDescGZIP(), []int{6}
}

func (x *DecryptMetadataResponse) GetDecryptedMetadata() []string {
	if x != nil {
		return x.DecryptedMetadata
	}
	return nil
}

func (x *DecryptMetadataResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_vault_service_proto protoreflect.FileDescriptor

const file_vault_service_proto_rawDesc = "" +
	"\n" +
	"\x13vault_service.proto\x12\rrune.vault.v1\x1a\x1bbuf/validate/validate.proto\"6\n" +
	"\x13GetPublicKeyRequest\x12\x1f\n" +
	"\x05token\x18\x01 \x01(\tB\t\xbaH\x06r\x04\x10$\x18$R\x05token\"T\n" +
	"\x14GetPublicKeyResponse\x12&\n" +
	"\x0fkey_bundle_json\x18\x01 \x01(\tR\rkeyBundleJson\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x8f\x01\n" +
	"\x14DecryptScoresRequest\x12\x1f\n" +
	"\x05token\x18\x01 \x01(\tB\t\xbaH\x06r\x04\x10$\x18$R\x05token\x125\n" +
	"\x12encrypted_blob_b64\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x10encryptedBlobB64\x12\x1f\n" +
	"\x05top_k\x18\x03 \x01(\x05B\n" +
	"\xbaH\a\x1a\x05\x18\xac\x02(\x01R\x04topK\"X\n" +
	"\n" +
	"ScoreEntry\x12\x1b\n" +
	"\tshard_idx\x18\x01 \x01(\x05R\bshardIdx\x12\x17\n" +
	"\arow_idx\x18\x02 \x01(\x05R\x06rowIdx\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x01R\x05score\"b\n" +
	"\x15DecryptScoresResponse\x123\n" +
	"\aresults\x18\x01 \x03(\v2\x19.rune.vault.v1.ScoreEntryR\aresults\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x84\x01\n" +
	"\x16DecryptMetadataRequest\x12\x1f\n" +
	"\x05token\x18\x01 \x01(\tB\t\xbaH\x06r\x04\x10$\x18$R\x05token\x12I\n" +
	"\x17encrypted_metadata_list\x18\x02 \x03(\tB\x11\xbaH\x0e\x92\x01\v\b\x01\x10\xe8\a\"\x04r\x02\x10\x01R\x15encryptedMetadataList\"^\n" +
	"\x17DecryptMetadataResponse\x12-\n" +
	"\x12decrypted_metadata\x18\x01 \x03(\tR\x11decryptedMetadata\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2\xa5\x02\n" +
	"\fVaultService\x12W\n" +
	"\fGetPublicKey\x12\".rune.vault.v1.GetPublicKeyRequest\x1a#.rune.vault.v1.GetPublicKeyResponse\x12Z\n" +
	"\rDecryptScores\x12#.rune.vault.v1.DecryptScoresRequest\x1a$.rune.vault.v1.DecryptScoresResponse\x12`\n" +
	"\x0fDecryptMetadata\x12%.rune.vault.v1.DecryptMetadataRequest\x1a&.rune.vault.v1.DecryptMetadataResponseb\x06proto3"

var (
	file_vault_service_proto_rawDescOnce sync.Once
	file_vault_service_proto_rawDescData []byte
)

func file_vault_service_proto_rawDescGZIP() []byte {
	file_vault_service_proto_rawDescOnce.Do(func() {
		file_vault_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vault_service_proto_rawDesc), len(file_vault_service_proto_rawDesc)))
	})
	return file_vault_service_proto_rawDescData
}

var file_vault_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_vault_service_proto_goTypes = []any{
	(*GetPublicKeyRequest)(nil),     // 0: rune.vault.v1.GetPublicKeyRequest
	(*GetPublicKeyResponse)(nil),    // 1: rune.vault.v1.GetPublicKeyResponse
	(*DecryptScoresRequest)(nil),    // 2: rune.vault.v1.DecryptScoresRequest
	(*ScoreEntry)(nil),              // 3: rune.vault.v1.ScoreEntry
	(*DecryptScoresResponse)(nil),   // 4: rune.vault.v1.DecryptScoresResponse
	(*DecryptMetadataRequest)(nil),  // 5: rune.vault.v1.DecryptMetadataRequest
	(*DecryptMetadataResponse)(nil), // 6: rune.vault.v1.DecryptMetadataResponse
}
var file_vault_service_proto_depIdxs = []int32{
	3, // 0: rune.vault.v1.DecryptScoresResponse.results:type_name -> rune.vault.v1.ScoreEntry
	0, // 1: rune.vault.v1.VaultService.GetPublicKey:input_type -> rune.vault.v1.GetPublicKeyRequest
	2, // 2: rune.vault.v1.VaultService.DecryptScores:input_type -> rune.vault.v1.DecryptScoresRequest
	5, // 3: rune.vault.v1.VaultService.DecryptMetadata:input_type -> rune.vault.v1.DecryptMetadataRequest
	1, // 4: rune.vault.v1.VaultService.GetPublicKey:output_type -> rune.vault.v1.GetPublicKeyResponse
	4, // 5: rune.vault.v1.VaultService.DecryptScores:output_type -> rune.vault.v1.DecryptScoresResponse
	6, // 6: rune.vault.v1.VaultService.DecryptMetadata:output_type -> rune.vault.v1.DecryptMetadataResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_vault_service_proto_init() }
func file_vault_service_proto_init() {
	if File_vault_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vault_service_proto_rawDesc), len(file_vault_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vault_service_proto_goTypes,
		DependencyIndexes: file_vault_service_proto_depIdxs,
		MessageInfos:      file_vault_service_proto_msgTypes,
	}.Build()
	File_vault_service_proto = out.File
	file_vault_service_proto_goTypes = nil
	file_vault_service_proto_depIdxs = nil
}
