// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: vault_service.proto

package vaultpb

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAgentManifestRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Auth token. Required, fixed 36 chars (evt_ + 32 hex).
	Token         string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentManifestRequest) Reset() {
	*x = GetAgentManifestRequest{}
	mi := &file_vault_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentManifestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentManifestRequest) ProtoMessage() {}

func (x *GetAgentManifestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vault_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentManifestRequest.ProtoReflect.Descriptor instead.
func (*GetAgentManifestRequest) Descriptor() ([]byte, []int) {
	return file_vault_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetAgentManifestRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type GetAgentManifestResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// JSON: {"index_name": "...", "agent_id": "...", "dim": 1024} — no keys.
	ManifestJson  string `protobuf:"bytes,1,opt,name=manifest_json,json=manifestJson,proto3" json:"manifest_json,omitempty"`
	Error         string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"` // Non-empty on error
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentManifestResponse) Reset() {
	*x = GetAgentManifestResponse{}
	mi := &file_vault_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentManifestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentManifestResponse) ProtoMessage() {}

func (x *GetAgentManifestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vault_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentManifestResponse.ProtoReflect.Descriptor instead.
func (*GetAgentManifestResponse) Descriptor() ([]byte, []int) {
	return file_vault_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetAgentManifestResponse) GetManifestJson() string {
	if x != nil {
		return x.ManifestJson
	}
	return ""
}

func (x *GetAgentManifestResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type InsertRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Auth token. Required, fixed 36 chars.
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// Plaintext embedding (runed output). Length must equal the configured dim.
	Vector []float32 `protobuf:"fixed32,2,rep,packed,name=vector,proto3" json:"vector,omitempty"`
	// Plaintext metadata JSON. Vault seals it (agent_dek) before storing; may be empty.
	Metadata      string `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertRequest) Reset() {
	*x = InsertRequest{}
	mi := &file_vault_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertRequest) ProtoMessage() {}

func (x *InsertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vault_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertRequest.ProtoReflect.Descriptor instead.
func (*InsertRequest) Descriptor() ([]byte, []int) {
	return file_vault_service_proto_rawDescGZIP(), []int{2}
}

func (x *InsertRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *InsertRequest) GetVector() []float32 {
	if x != nil {
		return x.Vector
	}
	return nil
}

func (x *InsertRequest) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

type InsertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`       // runespace-issued opaque id
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"` // Non-empty on error
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertResponse) Reset() {
	*x = InsertResponse{}
	mi := &file_vault_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertResponse) ProtoMessage() {}

func (x *InsertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vault_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertResponse.ProtoReflect.Descriptor instead.
func (*InsertResponse) Descriptor() ([]byte, []int) {
	return file_vault_service_proto_rawDescGZIP(), []int{3}
}

func (x *InsertResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InsertResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SearchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Auth token. Required, fixed 36 chars.
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// Plaintext query embedding. Length must equal the configured dim.
	Vector []float32 `protobuf:"fixed32,2,rep,packed,name=vector,proto3" json:"vector,omitempty"`
	// Number of top results. Per-role limits enforced at the business logic layer.
	TopK          int32 `protobuf:"varint,3,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_vault_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vault_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_vault_service_proto_rawDescGZIP(), []int{4}
}

func (x *SearchRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *SearchRequest) GetVector() []float32 {
	if x != nil {
		return x.Vector
	}
	return nil
}

func (x *SearchRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

type SearchHit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Score         float64                `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`
	Metadata      string                 `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"` // plaintext JSON (vault opened the agent_dek envelope)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchHit) Reset() {
	*x = SearchHit{}
	mi := &file_vault_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchHit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchHit) ProtoMessage() {}

func (x *SearchHit) ProtoReflect() protoreflect.Message {
	mi := &file_vault_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchHit.ProtoReflect.Descriptor instead.
func (*SearchHit) Descriptor() ([]byte, []int) {
	return file_vault_service_proto_rawDescGZIP(), []int{5}
}

func (x *SearchHit) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SearchHit) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *SearchHit) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hits          []*SearchHit           `protobuf:"bytes,1,rep,name=hits,proto3" json:"hits,omitempty"`   // ranked, score descending
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"` // Non-empty on error
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_vault_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vault_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_vault_service_proto_rawDescGZIP(), []int{6}
}

func (x *SearchResponse) GetHits() []*SearchHit {
	if x != nil {
		return x.Hits
	}
	return nil
}

func (x *SearchResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_vault_service_proto protoreflect.FileDescriptor

const file_vault_service_proto_rawDesc = "" +
	"\n" +
	"\x13vault_service.proto\x12\rrune.vault.v1\x1a\x1bbuf/validate/validate.proto\":\n" +
	"\x17GetAgentManifestRequest\x12\x1f\n" +
	"\x05token\x18\x01 \x01(\tB\t\xbaH\x06r\x04\x10$\x18$R\x05token\"U\n" +
	"\x18GetAgentManifestResponse\x12#\n" +
	"\rmanifest_json\x18\x01 \x01(\tR\fmanifestJson\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"n\n" +
	"\rInsertRequest\x12\x1f\n" +
	"\x05token\x18\x01 \x01(\tB\t\xbaH\x06r\x04\x10$\x18$R\x05token\x12 \n" +
	"\x06vector\x18\x02 \x03(\x02B\b\xbaH\x05\x92\x01\x02\b\x01R\x06vector\x12\x1a\n" +
	"\bmetadata\x18\x03 \x01(\tR\bmetadata\"6\n" +
	"\x0eInsertResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"s\n" +
	"\rSearchRequest\x12\x1f\n" +
	"\x05token\x18\x01 \x01(\tB\t\xbaH\x06r\x04\x10$\x18$R\x05token\x12 \n" +
	"\x06vector\x18\x02 \x03(\x02B\b\xbaH\x05\x92\x01\x02\b\x01R\x06vector\x12\x1f\n" +
	"\x05top_k\x18\x03 \x01(\x05B\n" +
	"\xbaH\a\x1a\x05\x18\xac\x02(\x01R\x04topK\"M\n" +
	"\tSearchHit\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x01R\x05score\x12\x1a\n" +
	"\bmetadata\x18\x03 \x01(\tR\bmetadata\"T\n" +
	"\x0eSearchResponse\x12,\n" +
	"\x04hits\x18\x01 \x03(\v2\x18.rune.vault.v1.SearchHitR\x04hits\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2\x81\x02\n" +
	"\fVaultService\x12c\n" +
	"\x10GetAgentManifest\x12&.rune.vault.v1.GetAgentManifestRequest\x1a'.rune.vault.v1.GetAgentManifestResponse\x12E\n" +
	"\x06Insert\x12\x1c.rune.vault.v1.InsertRequest\x1a\x1d.rune.vault.v1.InsertResponse\x12E\n" +
	"\x06Search\x12\x1c.rune.vault.v1.SearchRequest\x1a\x1d.rune.vault.v1.SearchResponseb\x06proto3"

var (
	file_vault_service_proto_rawDescOnce sync.Once
	file_vault_service_proto_rawDescData []byte
)

func file_vault_service_proto_rawDescGZIP() []byte {
	file_vault_service_proto_rawDescOnce.Do(func() {
		file_vault_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vault_service_proto_rawDesc), len(file_vault_service_proto_rawDesc)))
	})
	return file_vault_service_proto_rawDescData
}

var file_vault_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_vault_service_proto_goTypes = []any{
	(*GetAgentManifestRequest)(nil),  // 0: rune.vault.v1.GetAgentManifestRequest
	(*GetAgentManifestResponse)(nil), // 1: rune.vault.v1.GetAgentManifestResponse
	(*InsertRequest)(nil),            // 2: rune.vault.v1.InsertRequest
	(*InsertResponse)(nil),           // 3: rune.vault.v1.InsertResponse
	(*SearchRequest)(nil),            // 4: rune.vault.v1.SearchRequest
	(*SearchHit)(nil),                // 5: rune.vault.v1.SearchHit
	(*SearchResponse)(nil),           // 6: rune.vault.v1.SearchResponse
}
var file_vault_service_proto_depIdxs = []int32{
	5, // 0: rune.vault.v1.SearchResponse.hits:type_name -> rune.vault.v1.SearchHit
	0, // 1: rune.vault.v1.VaultService.GetAgentManifest:input_type -> rune.vault.v1.GetAgentManifestRequest
	2, // 2: rune.vault.v1.VaultService.Insert:input_type -> rune.vault.v1.InsertRequest
	4, // 3: rune.vault.v1.VaultService.Search:input_type -> rune.vault.v1.SearchRequest
	1, // 4: rune.vault.v1.VaultService.GetAgentManifest:output_type -> rune.vault.v1.GetAgentManifestResponse
	3, // 5: rune.vault.v1.VaultService.Insert:output_type -> rune.vault.v1.InsertResponse
	6, // 6: rune.vault.v1.VaultService.Search:output_type -> rune.vault.v1.SearchResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_vault_service_proto_init() }
func file_vault_service_proto_init() {
	if File_vault_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vault_service_proto_rawDesc), len(file_vault_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vault_service_proto_goTypes,
		DependencyIndexes: file_vault_service_proto_depIdxs,
		MessageInfos:      file_vault_service_proto_msgTypes,
	}.Build()
	File_vault_service_proto = out.File
	file_vault_service_proto_goTypes = nil
	file_vault_service_proto_depIdxs = nil
}
