// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: vault_service.proto

package vaultpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VaultService_GetAgentManifest_FullMethodName = "/rune.vault.v1.VaultService/GetAgentManifest"
	VaultService_DecryptScores_FullMethodName    = "/rune.vault.v1.VaultService/DecryptScores"
	VaultService_DecryptMetadata_FullMethodName  = "/rune.vault.v1.VaultService/DecryptMetadata"
)

// VaultServiceClient is the client API for VaultService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Rune-Vault gRPC service.
// Holds the FHE secret key and performs all decryption operations.
type VaultServiceClient interface {
	// Returns the agent manifest (EncKey, agent credentials, optional team index name).
	GetAgentManifest(ctx context.Context, in *GetAgentManifestRequest, opts ...grpc.CallOption) (*GetAgentManifestResponse, error)
	// Decrypts FHE-encrypted similarity scores and applies Top-K filtering.
	DecryptScores(ctx context.Context, in *DecryptScoresRequest, opts ...grpc.CallOption) (*DecryptScoresResponse, error)
	// Decrypts a list of AES-encrypted metadata strings.
	DecryptMetadata(ctx context.Context, in *DecryptMetadataRequest, opts ...grpc.CallOption) (*DecryptMetadataResponse, error)
}

type vaultServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVaultServiceClient(cc grpc.ClientConnInterface) VaultServiceClient {
	return &vaultServiceClient{cc}
}

func (c *vaultServiceClient) GetAgentManifest(ctx context.Context, in *GetAgentManifestRequest, opts ...grpc.CallOption) (*GetAgentManifestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAgentManifestResponse)
	err := c.cc.Invoke(ctx, VaultService_GetAgentManifest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vaultServiceClient) DecryptScores(ctx context.Context, in *DecryptScoresRequest, opts ...grpc.CallOption) (*DecryptScoresResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DecryptScoresResponse)
	err := c.cc.Invoke(ctx, VaultService_DecryptScores_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vaultServiceClient) DecryptMetadata(ctx context.Context, in *DecryptMetadataRequest, opts ...grpc.CallOption) (*DecryptMetadataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DecryptMetadataResponse)
	err := c.cc.Invoke(ctx, VaultService_DecryptMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VaultServiceServer is the server API for VaultService service.
// All implementations must embed UnimplementedVaultServiceServer
// for forward compatibility.
//
// Rune-Vault gRPC service.
// Holds the FHE secret key and performs all decryption operations.
type VaultServiceServer interface {
	// Returns the agent manifest (EncKey, agent credentials, optional team index name).
	GetAgentManifest(context.Context, *GetAgentManifestRequest) (*GetAgentManifestResponse, error)
	// Decrypts FHE-encrypted similarity scores and applies Top-K filtering.
	DecryptScores(context.Context, *DecryptScoresRequest) (*DecryptScoresResponse, error)
	// Decrypts a list of AES-encrypted metadata strings.
	DecryptMetadata(context.Context, *DecryptMetadataRequest) (*DecryptMetadataResponse, error)
	mustEmbedUnimplementedVaultServiceServer()
}

// UnimplementedVaultServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVaultServiceServer struct{}

func (UnimplementedVaultServiceServer) GetAgentManifest(context.Context, *GetAgentManifestRequest) (*GetAgentManifestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAgentManifest not implemented")
}
func (UnimplementedVaultServiceServer) DecryptScores(context.Context, *DecryptScoresRequest) (*DecryptScoresResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DecryptScores not implemented")
}
func (UnimplementedVaultServiceServer) DecryptMetadata(context.Context, *DecryptMetadataRequest) (*DecryptMetadataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DecryptMetadata not implemented")
}
func (UnimplementedVaultServiceServer) mustEmbedUnimplementedVaultServiceServer() {}
func (UnimplementedVaultServiceServer) testEmbeddedByValue()                      {}

// UnsafeVaultServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VaultServiceServer will
// result in compilation errors.
type UnsafeVaultServiceServer interface {
	mustEmbedUnimplementedVaultServiceServer()
}

func RegisterVaultServiceServer(s grpc.ServiceRegistrar, srv VaultServiceServer) {
	// If the following call panics, it indicates UnimplementedVaultServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VaultService_ServiceDesc, srv)
}

func _VaultService_GetAgentManifest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAgentManifestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VaultServiceServer).GetAgentManifest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VaultService_GetAgentManifest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VaultServiceServer).GetAgentManifest(ctx, req.(*GetAgentManifestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VaultService_DecryptScores_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecryptScoresRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VaultServiceServer).DecryptScores(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VaultService_DecryptScores_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VaultServiceServer).DecryptScores(ctx, req.(*DecryptScoresRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VaultService_DecryptMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecryptMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VaultServiceServer).DecryptMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VaultService_DecryptMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VaultServiceServer).DecryptMetadata(ctx, req.(*DecryptMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VaultService_ServiceDesc is the grpc.ServiceDesc for VaultService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VaultService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rune.vault.v1.VaultService",
	HandlerType: (*VaultServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAgentManifest",
			Handler:    _VaultService_GetAgentManifest_Handler,
		},
		{
			MethodName: "DecryptScores",
			Handler:    _VaultService_DecryptScores_Handler,
		},
		{
			MethodName: "DecryptMetadata",
			Handler:    _VaultService_DecryptMetadata_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vault_service.proto",
}
