# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import vault_service_pb2 as vault__service__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in vault_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VaultServiceStub(object):
    """Rune-Vault gRPC service.
    Holds the FHE secret key and performs all decryption operations.
    Phase 1: dual-stack alongside FastMCP HTTP/SSE (port 50080).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPublicKey = channel.unary_unary(
                '/rune.vault.v1.VaultService/GetPublicKey',
                request_serializer=vault__service__pb2.GetPublicKeyRequest.SerializeToString,
                response_deserializer=vault__service__pb2.GetPublicKeyResponse.FromString,
                _registered_method=True)
        self.DecryptScores = channel.unary_unary(
                '/rune.vault.v1.VaultService/DecryptScores',
                request_serializer=vault__service__pb2.DecryptScoresRequest.SerializeToString,
                response_deserializer=vault__service__pb2.DecryptScoresResponse.FromString,
                _registered_method=True)
        self.DecryptMetadata = channel.unary_unary(
                '/rune.vault.v1.VaultService/DecryptMetadata',
                request_serializer=vault__service__pb2.DecryptMetadataRequest.SerializeToString,
                response_deserializer=vault__service__pb2.DecryptMetadataResponse.FromString,
                _registered_method=True)


class VaultServiceServicer(object):
    """Rune-Vault gRPC service.
    Holds the FHE secret key and performs all decryption operations.
    Phase 1: dual-stack alongside FastMCP HTTP/SSE (port 50080).
    """

    def GetPublicKey(self, request, context):
        """Returns the public key bundle (EncKey, EvalKey, optional team index name).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DecryptScores(self, request, context):
        """Decrypts FHE-encrypted similarity scores and applies Top-K filtering.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DecryptMetadata(self, request, context):
        """Decrypts a list of AES-encrypted metadata strings.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VaultServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPublicKey': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPublicKey,
                    request_deserializer=vault__service__pb2.GetPublicKeyRequest.FromString,
                    response_serializer=vault__service__pb2.GetPublicKeyResponse.SerializeToString,
            ),
            'DecryptScores': grpc.unary_unary_rpc_method_handler(
                    servicer.DecryptScores,
                    request_deserializer=vault__service__pb2.DecryptScoresRequest.FromString,
                    response_serializer=vault__service__pb2.DecryptScoresResponse.SerializeToString,
            ),
            'DecryptMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.DecryptMetadata,
                    request_deserializer=vault__service__pb2.DecryptMetadataRequest.FromString,
                    response_serializer=vault__service__pb2.DecryptMetadataResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rune.vault.v1.VaultService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rune.vault.v1.VaultService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VaultService(object):
    """Rune-Vault gRPC service.
    Holds the FHE secret key and performs all decryption operations.
    Phase 1: dual-stack alongside FastMCP HTTP/SSE (port 50080).
    """

    @staticmethod
    def GetPublicKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rune.vault.v1.VaultService/GetPublicKey',
            vault__service__pb2.GetPublicKeyRequest.SerializeToString,
            vault__service__pb2.GetPublicKeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DecryptScores(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rune.vault.v1.VaultService/DecryptScores',
            vault__service__pb2.DecryptScoresRequest.SerializeToString,
            vault__service__pb2.DecryptScoresResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DecryptMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rune.vault.v1.VaultService/DecryptMetadata',
            vault__service__pb2.DecryptMetadataRequest.SerializeToString,
            vault__service__pb2.DecryptMetadataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
