#!/bin/bash

# Rune Team Member Onboarding Script
# Automates the process of adding a new member to the team

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

print_header() {
    echo -e "\n${BLUE}================================================${NC}"
    echo -e "${BLUE}$1${NC}"
    echo -e "${BLUE}================================================${NC}\n"
}

print_success() {
    echo -e "${GREEN}✓ $1${NC}"
}

print_warning() {
    echo -e "${YELLOW}⚠ $1${NC}"
}

print_error() {
    echo -e "${RED}✗ $1${NC}"
}

print_info() {
    echo -e "${BLUE}ℹ $1${NC}"
}

# Configuration
VAULT_URL="${VAULT_URL:-}"
VAULT_TOKEN="${VAULT_TOKEN:-}"
TEAM_NAME="${TEAM_NAME:-}"
ENVECTOR_API_URL="${ENVECTOR_API_URL:-https://api.envector.io}"

print_header "Rune Team Member Onboarding"

# Validate environment
if [ -z "$VAULT_URL" ]; then
    print_error "VAULT_URL is not set"
    echo "Set with: export VAULT_URL=https://vault-yourteam.oci.envector.io"
    exit 1
fi

if [ -z "$VAULT_TOKEN" ]; then
    print_error "VAULT_TOKEN is not set"
    echo "Set with: export VAULT_TOKEN=evt_yourteam_xxx"
    exit 1
fi

if [ -z "$TEAM_NAME" ]; then
    print_error "TEAM_NAME is not set"
    echo "Set with: export TEAM_NAME=yourteam"
    exit 1
fi

print_success "Environment validated"
echo "  Vault URL: $VAULT_URL"
echo "  Team: $TEAM_NAME"
echo ""

# Get member information
read -p "New member's name: " MEMBER_NAME
read -p "New member's email: " MEMBER_EMAIL
read -p "Member's OS (macos/linux/windows): " MEMBER_OS

echo ""
print_info "Adding member: $MEMBER_NAME ($MEMBER_EMAIL)"
print_info "Operating System: $MEMBER_OS"
echo ""

# Generate member-specific configuration
MEMBER_ID=$(echo "$MEMBER_EMAIL" | md5sum | cut -d' ' -f1 | head -c 8)
CONFIG_FILE="${MEMBER_NAME// /_}_rune_config.json"
SETUP_SCRIPT="${MEMBER_NAME// /_}_setup.sh"

print_header "Generating Configuration"

# Create configuration file
cat > "$CONFIG_FILE" <<EOF
{
  "team_name": "$TEAM_NAME",
  "member_name": "$MEMBER_NAME",
  "member_email": "$MEMBER_EMAIL",
  "member_id": "$MEMBER_ID",
  "vault_url": "$VAULT_URL",
  "vault_token": "$VAULT_TOKEN",
  "envector_api_url": "$ENVECTOR_API_URL",
  "created_at": "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
}
EOF

print_success "Configuration file created: $CONFIG_FILE"

# Create setup script based on OS
print_header "Generating Setup Script"

if [ "$MEMBER_OS" = "windows" ]; then
    SETUP_SCRIPT="${MEMBER_NAME// /_}_setup.ps1"
    cat > "$SETUP_SCRIPT" <<'EOF'
# Rune Setup Script for Windows
# Generated by add-team-member.sh

Write-Host "==================================================" -ForegroundColor Blue
Write-Host "Rune Installation & Configuration" -ForegroundColor Blue
Write-Host "==================================================" -ForegroundColor Blue
Write-Host ""

# Configuration (auto-filled)
$VAULT_URL = "VAULT_URL_PLACEHOLDER"
$VAULT_TOKEN = "VAULT_TOKEN_PLACEHOLDER"
$TEAM_NAME = "TEAM_NAME_PLACEHOLDER"
$ENVECTOR_API_URL = "ENVECTOR_API_URL_PLACEHOLDER"

# Step 1: Clone Rune repository
Write-Host "Step 1: Cloning Rune repository..." -ForegroundColor Green
$RUNE_DIR = "$env:USERPROFILE\rune"
if (Test-Path $RUNE_DIR) {
    Write-Host "Rune directory already exists. Pulling latest..." -ForegroundColor Yellow
    Set-Location $RUNE_DIR
    git pull
} else {
    git clone https://github.com/CryptoLabInc/rune.git $RUNE_DIR
    Set-Location $RUNE_DIR
}

# Step 2: Install Rune
Write-Host "Step 2: Installing Rune..." -ForegroundColor Green
.\install.ps1

# Step 3: Configure Vault connection
Write-Host "Step 3: Configuring Vault connection..." -ForegroundColor Green
$CONFIG_PATH = "$env:USERPROFILE\.config\rune\vault-config.json"
New-Item -ItemType Directory -Force -Path (Split-Path $CONFIG_PATH) | Out-Null

$CONFIG = @{
    vault_url = $VAULT_URL
    vault_token = $VAULT_TOKEN
    team_name = $TEAM_NAME
    envector_api_url = $ENVECTOR_API_URL
} | ConvertTo-Json

Set-Content -Path $CONFIG_PATH -Value $CONFIG
Write-Host "Configuration saved: $CONFIG_PATH" -ForegroundColor Green

# Step 4: Test connection
Write-Host "Step 4: Testing Vault connection..." -ForegroundColor Green
try {
    $response = Invoke-RestMethod -Uri "$VAULT_URL/health" -Method Get -TimeoutSec 10
    Write-Host "✓ Vault is reachable!" -ForegroundColor Green
} catch {
    Write-Host "✗ Failed to reach Vault: $_" -ForegroundColor Red
    exit 1
}

# Step 5: Setup agent (Claude/Gemini/Codex)
Write-Host ""
Write-Host "Step 5: Agent Setup" -ForegroundColor Green
Write-Host "Choose your AI agent:" -ForegroundColor Yellow
Write-Host "  1) Claude (via Claude Desktop or Cline)"
Write-Host "  2) Gemini (via Gemini Desktop)"
Write-Host "  3) Codex (via VS Code Copilot)"
Write-Host ""
$AGENT_CHOICE = Read-Host "Enter choice (1-3)"

switch ($AGENT_CHOICE) {
    "1" {
        # Claude setup
        $CLAUDE_CONFIG = "$env:APPDATA\Claude\config.json"
        Write-Host "Add this to your Claude config ($CLAUDE_CONFIG):" -ForegroundColor Yellow
        Write-Host @"
{
  "mcpServers": {
    "rune-vault": {
      "command": "npx",
      "args": ["-y", "@cryptolab/rune-mcp-client"],
      "env": {
        "VAULT_URL": "$VAULT_URL",
        "VAULT_TOKEN": "$VAULT_TOKEN"
      }
    }
  }
}
"@
    }
    "2" {
        # Gemini setup
        Write-Host "Gemini setup instructions:" -ForegroundColor Yellow
        Write-Host "1. Open Gemini Desktop settings"
        Write-Host "2. Add MCP server:"
        Write-Host "   - Name: rune-vault"
        Write-Host "   - Command: npx -y @cryptolab/rune-mcp-client"
        Write-Host "   - Env: VAULT_URL=$VAULT_URL, VAULT_TOKEN=$VAULT_TOKEN"
    }
    "3" {
        # Codex setup
        Write-Host "VS Code Copilot setup:" -ForegroundColor Yellow
        Write-Host "1. Install Rune extension: code --install-extension cryptolab.rune"
        Write-Host "2. Configure in VS Code settings (Ctrl+,):"
        Write-Host "   - Rune: Vault URL = $VAULT_URL"
        Write-Host "   - Rune: Vault Token = $VAULT_TOKEN"
    }
}

Write-Host ""
Write-Host "==================================================" -ForegroundColor Blue
Write-Host "Setup Complete!" -ForegroundColor Green
Write-Host "==================================================" -ForegroundColor Blue
Write-Host ""
Write-Host "Next steps:" -ForegroundColor Yellow
Write-Host "1. Restart your AI agent"
Write-Host "2. Test Rune: Ask agent 'What organizational context do we have?'"
Write-Host "3. Join team channel for support"
Write-Host ""
EOF

    # Replace placeholders
    sed -i "s|VAULT_URL_PLACEHOLDER|$VAULT_URL|g" "$SETUP_SCRIPT"
    sed -i "s|VAULT_TOKEN_PLACEHOLDER|$VAULT_TOKEN|g" "$SETUP_SCRIPT"
    sed -i "s|TEAM_NAME_PLACEHOLDER|$TEAM_NAME|g" "$SETUP_SCRIPT"
    sed -i "s|ENVECTOR_API_URL_PLACEHOLDER|$ENVECTOR_API_URL|g" "$SETUP_SCRIPT"

else
    # macOS/Linux setup script
    cat > "$SETUP_SCRIPT" <<'EOF'
#!/bin/bash

# Rune Setup Script for macOS/Linux
# Generated by add-team-member.sh

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

print_header() {
    echo -e "\n${BLUE}================================================${NC}"
    echo -e "${BLUE}$1${NC}"
    echo -e "${BLUE}================================================${NC}\n"
}

print_success() {
    echo -e "${GREEN}✓ $1${NC}"
}

print_error() {
    echo -e "${RED}✗ $1${NC}"
}

# Configuration (auto-filled)
VAULT_URL="VAULT_URL_PLACEHOLDER"
VAULT_TOKEN="VAULT_TOKEN_PLACEHOLDER"
TEAM_NAME="TEAM_NAME_PLACEHOLDER"
ENVECTOR_API_URL="ENVECTOR_API_URL_PLACEHOLDER"

print_header "Rune Installation & Configuration"

# Step 1: Clone Rune repository
print_header "Step 1: Cloning Rune repository"
RUNE_DIR="$HOME/rune"
if [ -d "$RUNE_DIR" ]; then
    echo "Rune directory already exists. Pulling latest..."
    cd "$RUNE_DIR" && git pull
else
    git clone https://github.com/CryptoLabInc/rune.git "$RUNE_DIR"
    cd "$RUNE_DIR"
fi
print_success "Repository cloned"

# Step 2: Install Rune
print_header "Step 2: Installing Rune"
./install.sh
print_success "Rune installed"

# Step 3: Configure Vault connection
print_header "Step 3: Configuring Vault connection"
CONFIG_DIR="$HOME/.config/rune"
CONFIG_FILE="$CONFIG_DIR/vault-config.json"
mkdir -p "$CONFIG_DIR"

cat > "$CONFIG_FILE" <<EOFCONFIG
{
  "vault_url": "$VAULT_URL",
  "vault_token": "$VAULT_TOKEN",
  "team_name": "$TEAM_NAME",
  "envector_api_url": "$ENVECTOR_API_URL"
}
EOFCONFIG

chmod 600 "$CONFIG_FILE"
print_success "Configuration saved: $CONFIG_FILE"

# Step 4: Test connection
print_header "Step 4: Testing Vault connection"
if curl -s --max-time 10 "$VAULT_URL/health" > /dev/null 2>&1; then
    print_success "Vault is reachable!"
else
    print_error "Failed to reach Vault at $VAULT_URL"
    exit 1
fi

# Step 5: Setup agent
print_header "Step 5: Agent Setup"
echo "Choose your AI agent:"
echo "  1) Claude (via Claude Desktop or Cline)"
echo "  2) Gemini (via Gemini Desktop)"
echo "  3) Codex (via VS Code Copilot)"
echo ""
read -p "Enter choice (1-3): " AGENT_CHOICE

case $AGENT_CHOICE in
    1)
        # Claude setup
        CLAUDE_CONFIG="$HOME/Library/Application Support/Claude/config.json"
        echo ""
        echo "Add this to your Claude config ($CLAUDE_CONFIG):"
        echo ""
        cat <<CLAUDECONFIG
{
  "mcpServers": {
    "rune-vault": {
      "command": "npx",
      "args": ["-y", "@cryptolab/rune-mcp-client"],
      "env": {
        "VAULT_URL": "$VAULT_URL",
        "VAULT_TOKEN": "$VAULT_TOKEN"
      }
    }
  }
}
CLAUDECONFIG
        ;;
    2)
        # Gemini setup
        echo ""
        echo "Gemini setup instructions:"
        echo "1. Open Gemini Desktop settings"
        echo "2. Add MCP server:"
        echo "   - Name: rune-vault"
        echo "   - Command: npx -y @cryptolab/rune-mcp-client"
        echo "   - Env: VAULT_URL=$VAULT_URL, VAULT_TOKEN=$VAULT_TOKEN"
        ;;
    3)
        # Codex setup
        echo ""
        echo "VS Code Copilot setup:"
        echo "1. Install Rune extension: code --install-extension cryptolab.rune"
        echo "2. Configure in VS Code settings:"
        echo "   - Rune: Vault URL = $VAULT_URL"
        echo "   - Rune: Vault Token = $VAULT_TOKEN"
        ;;
esac

print_header "Setup Complete!"
echo ""
echo "Next steps:"
echo "1. Restart your AI agent"
echo "2. Test Rune: Ask agent 'What organizational context do we have?'"
echo "3. Join team channel for support"
echo ""
EOF

    # Replace placeholders
    sed -i.bak "s|VAULT_URL_PLACEHOLDER|$VAULT_URL|g" "$SETUP_SCRIPT"
    sed -i.bak "s|VAULT_TOKEN_PLACEHOLDER|$VAULT_TOKEN|g" "$SETUP_SCRIPT"
    sed -i.bak "s|TEAM_NAME_PLACEHOLDER|$TEAM_NAME|g" "$SETUP_SCRIPT"
    sed -i.bak "s|ENVECTOR_API_URL_PLACEHOLDER|$ENVECTOR_API_URL|g" "$SETUP_SCRIPT"
    rm -f "${SETUP_SCRIPT}.bak"
    chmod +x "$SETUP_SCRIPT"
fi

print_success "Setup script created: $SETUP_SCRIPT"

# Create README for member
README_FILE="${MEMBER_NAME// /_}_README.md"
cat > "$README_FILE" <<EOF
# Rune Setup for $MEMBER_NAME

Welcome to the **$TEAM_NAME** team!

## Quick Start

### Step 1: Run Setup Script

**macOS/Linux:**
\`\`\`bash
chmod +x $SETUP_SCRIPT
./$SETUP_SCRIPT
\`\`\`

**Windows:**
\`\`\`powershell
powershell -ExecutionPolicy Bypass -File $SETUP_SCRIPT
\`\`\`

### Step 2: Configure Your Agent

The setup script will guide you through configuring your AI agent (Claude, Gemini, or Codex).

### Step 3: Test

Ask your agent:
> "What organizational context do we have?"

If Rune is configured correctly, your agent will retrieve team context from the Vault.

## Configuration Files

- **Config:** \`$CONFIG_FILE\`
- **Vault URL:** \`$VAULT_URL\`
- **Team:** \`$TEAM_NAME\`

## Important Security Notes

🔒 **Keep your Vault token secret!**
- Never commit \`$CONFIG_FILE\` to git
- Don't share your token in Slack/email
- If compromised, contact team admin to rotate

## Troubleshooting

### "Vault not reachable"
- Check VPN connection (if team uses VPN)
- Verify \`$VAULT_URL\` is correct
- Test: \`curl $VAULT_URL/health\`

### "Authentication failed"
- Verify \`VAULT_TOKEN\` is correct
- Contact team admin to verify your token is active

### "Agent not finding Rune"
- Restart your AI agent after configuration
- Check agent logs for MCP server errors
- Verify MCP server configuration

## Support

- **Team Admin:** [Your team admin email]
- **Rune Docs:** https://docs.envector.io
- **Issues:** https://github.com/CryptoLabInc/rune/issues

## Next Steps

1. Read [Rune Documentation](https://docs.envector.io)
2. Review team's organizational context
3. Start capturing decisions with Scribe agent
4. Join team collaboration channel

---

Generated on $(date)
EOF

print_success "README created: $README_FILE"

# Create package for member
PACKAGE_DIR="${MEMBER_NAME// /_}_rune_package"
mkdir -p "$PACKAGE_DIR"
mv "$CONFIG_FILE" "$SETUP_SCRIPT" "$README_FILE" "$PACKAGE_DIR/"

print_header "Onboarding Package Created"
print_success "Package directory: $PACKAGE_DIR"
echo ""
echo "Contents:"
ls -lh "$PACKAGE_DIR"
echo ""

# Create shareable archive
ARCHIVE_FILE="${MEMBER_NAME// /_}_rune_package.zip"
zip -r "$ARCHIVE_FILE" "$PACKAGE_DIR" > /dev/null
print_success "Archive created: $ARCHIVE_FILE"

print_header "Next Steps"
echo "1. Send $ARCHIVE_FILE to $MEMBER_NAME via secure channel"
echo "2. Instruct them to extract and run the setup script"
echo "3. Verify their access with a test query"
echo ""
print_warning "Remember: Share via encrypted email or secure file transfer!"
echo ""

print_header "Onboarding Complete"
print_success "Member $MEMBER_NAME is ready to join!"
